version: '3.1'
services:
  ease-api:
    build:
      context: .
    volumes:
      - ./src:/usr/src/app/src
      - ./storage:/usr/src/app/storage
    ports:
      - ${PORT}:3001
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '3001']
      interval: 20s
      timeout: 5s
      retries: 3
    command: npm run dev